version: "3.8"

services:
  api:
    container_name: cefitem-backend
    build: .
    image: cefitem-backend
    ports:
      - 8080:8080
    env_file: ./.env

  rabbitmq:
    image: rabbitmq:3.7.28-management
    container_name: 'rabbit-mq'
    environment:
      - RABBITMQ_DEFAULT_USER=mercury
      - RABBITMQ_DEFAULT_PASS=kGGnN95q99Sh
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./etc/rabbitmq/conf:/etc/rabbitmq/
      - ./etc/rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ./etc/rabbitmq/logs/:/var/log/rabbitmq/
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
