version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbit-mq'
    environment:
      - RABBITMQ_DEFAULT_USER=mercury
      - RABBITMQ_DEFAULT_PASS=kGGnN95q99Sh
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./etc/rabbitmq/conf:/etc/rabbitmq/
      - ./etc/rabbitmq/data/:/var/lib/rabbitmq/
      - ./etc/rabbitmq/logs/:/var/log/rabbitmq/
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
